AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend services for the Aviation Weather Alexa skill

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  MetarFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: metar.lambda_handler
      Runtime: python3.8
      Events:
        Metar:
          Type: AlexaSkill
          Properties:
            SkillId: amzn1.ask.skill.fe6f20f5-3540-49e1-9062-7b79fd55a585

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MetarFunction:
    Description: "METAR Lambda Function ARN"
    Value: !GetAtt MetarFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for METAR function"
    Value: !GetAtt MetarFunctionRole.Arn
